#!/bin/bash
##
# Copyright 2016 Peerchemist <peerchemist@protonmail.ch> 
##

VERSION="0.2"

set_torrc() {
    echo "HiddenServiceDir /var/lib/tor/nu-service/" >> /etc/tor/torrc
    echo "HiddenServicePort 7890 127.0.0.1:7890" >> /etc/tor/torrc
}

if grep -Fxq "HiddenServiceDir /var/lib/tor/nu-service/" /etc/tor/torrc
then
    exit
else
    set_torrc
    if [ "`systemctl is-active tor.service`" != "active" ]
    then
    	exit
    else
    	systemctl stop tor.service
    	exit
    fi
fi